### PR TITLE
Actually fix UTF-8 encoding

### PR DESCRIPTION
**Pull request by NicoNekoDev**

### CODE REVIEW

**Comment by NicoNekoDev** [comment]
Here found the fix: https://stackoverflow.com/questions/35132693/set-encoding-as-utf-8-for-a-filewriter/35135497
Please note, if this might still not work, use `BufferedWriter`.
Another note is to have all different resources into multiple separate resource-initialization statements of the try-catch clause.

```        try (BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(file, true), StandardCharsets.UTF_8)) {
            new Yaml(options).dump(map, bw );
        } catch (IOException e) {```

**Review by NicoNekoDev — COMMENTED** [review]
That's even better if you use `JsonElement` but initializing a new gson builder everytime affects speed.

**Comment by divios** [comment]
Oh you are right, didn't saw your static gson hehe, I was scratching my head like, did he actually miss to include that? Thx again

**Comment by NicoNekoDev** [comment]
Well, to be fair, that gson change was only for speed improvements.

**Pull request merged**
